###########
# site.url, site.title
title: 'Data.gov ATO'

## note:
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
baseurl: /datagovATO
markdown: redcarpet
highlighter: pygments
sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md

safe: false

collections:
  - controls
  - system
